#define k 50
#define f 10
#define h 5


{

 int f[]={4,6,8}; 6
 int n;         2
 int num[f][h]; 100    
 int j;         2
 float a,b,c;   4+4+4
 struct KuKu
 {
	int s,m[10][5],n;   2+2+50*2
	float dam;          4 
	long double g;      10
	long w;             4
	char vvvvv[k];      50
 } data,fat;                344

 long double m[3][f],fgh,h[5][h]; 300+250+10=560

 long b,g[2][h]; 4+40=44

 struct MuMu{
		int name; 2
		long gui[f],gh[2][h]; 40+40=80
		double g;}; 8+80+2=90

 char cbnm[]="1234567890";
 int golrro(int,int);
 int i; 2
 MuMu d[2],g; 180+90=270;

}
 int func(int a, int b)
 {
	float a[f]; 40
	int s[2]; 4
 }